# Generated by Django 6.0.1 on 2026-01-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_total_amount_order_unit_price_ht_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='unit_price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
