# Generated by Django 6.0.1 on 2026-01-10 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_order_unit_price_ht'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='unit_price_ht',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='price_ht',
            new_name='price',
        ),
    ]
