# Generated by Django 6.0.1 on 2026-01-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_unit_price_ht_order_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='total_capacity',
            field=models.IntegerField(default=100),
        ),
    ]
