# Generated by Django 6.0.1 on 2026-01-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_user_wallet_balance_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'À venir'), ('ongoing', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('deleted', 'Supprimé')], default='upcoming', max_length=20),
        ),
    ]
