# Generated by Django 6.0.1 on 2026-01-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='available_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
